import { SLOT_TYPES } from "./slots.js";

const TOP_ONLY_VISIBLE_SLOT_TYPES = new Set([
  SLOT_TYPES.PILE,
  SLOT_TYPES.DECK,
  SLOT_TYPES.TABLE,
]);

const NEVER_DRAGGABLE_SLOT_TYPES = new Set([
  SLOT_TYPES.PILE,
  SLOT_TYPES.TABLE,
]);

const TOP_ONLY_DRAGGABLE_SLOT_TYPES = new Set([
  SLOT_TYPES.BENCH,
]);

export {
  NEVER_DRAGGABLE_SLOT_TYPES,
  TOP_ONLY_DRAGGABLE_SLOT_TYPES,
  TOP_ONLY_VISIBLE_SLOT_TYPES,
};
